Fixed unsupported operations
Romitou/MongoSK pull request #21
Opened 2021-02-19 01:41 UTC by Olyno

This pull request should fix #20. The main issue is ``Document#getList`` which returns an immutable list, so you can't change it. By casting this list to an ``ArrayList``, you should be able to make changes.

⚠️ This pull request has not been tested due to the lazy developer (me), please be sure there is no problem with it, at your own risks ⚠️

2021-02-19 01:44 UTC, Olyno commented
@EarthAgar can you try this artifact and check if your issue is solved please?

[Download the artifact by clicking here](https://github.com/Romitou/MongoSK/suites/2073855627/artifacts/41955666)

2021-02-19 02:44 UTC, EarthAgar commented
No it doesn't fix the issue, here is the error given: https://paste.helpch.at/oyeyefegay.md

By any chance will it ever be possible to set values to locations without having to stringify them?

This artifact also seems to interfere with a condition of mine `if (level of blast protection of event-slot ? 0) < 5:`
![image](https://user-images.githubusercontent.com/27425322/108449873-152dbd00-7219-11eb-9142-d3f28e1aa15e.png)

2021-02-19 03:38 UTC, Olyno commented
Well my bad, I didn't expect to get a `null`` from Mongodb's driver. Anyway, can you try the next artifact when github action would let build it without any timeout and report me any other errors please?
@Romitou Please fix github's actions if you can (timeout thing, maybe rerun later?) 🙏🏻

2021-02-19 03:53 UTC, EarthAgar commented
I don't quite understand how to do what you want here: `can you try the next artifact when github action would let build it without any timeout`

2021-02-19 09:57 UTC, Olyno commented
I simply mean [this artifact](https://github.com/Romitou/MongoSK/suites/2074382101/artifacts/42012138), was waiting the fix of the github action for that

2021-02-19 11:15 UTC, Romitou requested changes
good catch! this is indeed what was wrong
i have made a few remarks, do not hesitate to tell me what you think about it

2021-02-19 11:15 UTC, Romitou commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                ArrayList<Object> list = new ArrayList<>(document.getList(value, Object.class));
i think we should keep the null check here as the `Document#getList` method can return a null list
i also think that in this case it is not necessary to create an arraylist, what do you think?

2021-02-19 11:15 UTC, Romitou commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                    ArrayList<Object> addList = new ArrayList<>(document.getList(value, Object.class));
as stated in my first comment, i think we should check if the list is not null before create an arraylist
since `addList` list can not be in the document, we can simply make a `Document#put` to create the list
```suggestion
                    List<Object> addList = document.getList(value, Object.class);
                    if (addList == null) {
                        document.put(value, deltaList);
                        return;
                    }
                    ArrayList<Object> addList = new ArrayList<>(addList);
```

2021-02-19 11:15 UTC, Romitou commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                    addList.addAll(deltaList);
the arraylist is updated, but not the document
i think we should make a `Document#put` (like when the `addList` is null) to update the list

2021-02-19 11:15 UTC, Romitou commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                    ArrayList<Object> removeList = new ArrayList<>(document.getList(value, Object.class));
same comments as for the `ADD`

2021-02-19 11:59 UTC, Olyno commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                ArrayList<Object> list = new ArrayList<>(document.getList(value, Object.class));
``getList`` returns an immutable list, so we must wrap it to avoid the ``UnsupportedOperation`` (refers to [this stackoverflow answer](https://stackoverflow.com/a/5755510/8845770)).
For the null check, I don't find it usefull in that case because you already have a try/catch, so we should use it more we can.

2021-02-19 12:03 UTC, Olyno commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                    ArrayList<Object> addList = new ArrayList<>(document.getList(value, Object.class));
If there is any null somewhere, the catch will be triggered, so needn't to check if it's null or not.
Nice on for the ``Document#put`` 🦄 (my editor told me it was a dead code, I didn't check my bad)

2021-02-19 12:14 UTC, Olyno commented
@EarthAgar Can you try [this artifact](https://github.com/Romitou/MongoSK/suites/2077283796/artifacts/42042315) please? Evertyhing should be fixed with this one (I hope 😁)

2021-02-19 13:05 UTC, Romitou commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                ArrayList<Object> list = new ArrayList<>(document.getList(value, Object.class));
we never modify the immutable list here, we should only return a mutable array with the `List#toArray` method in my opinion
alright for the try/catch

2021-02-19 13:06 UTC, Romitou commented on src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java
> +                    ArrayList<Object> addList = new ArrayList<>(document.getList(value, Object.class));
the problem here is if the addList is null, nothing will happen due to the try/catch
however, if the list is null, so if the list doesn't exist in the document, we must create it

2021-02-19 13:54 UTC, Olyno commented
Here is [the new artifact](https://github.com/Romitou/MongoSK/suites/2077981884/artifacts/42061605) to test ahahah

2021-02-19 19:10 UTC, Romitou approved these changes
Looks good to me! Thank you very much for your PR 😁

2021-02-19 19:11 UTC, merged

2021-02-19 19:31 UTC, EarthAgar commented
Yup seems to work for me. I don't know what to call it but I'm getting a false check for a mongo documents tho. I wish I could explain it better but here is the error: 
![image](https://user-images.githubusercontent.com/27425322/108552352-09d4a300-72a6-11eb-9543-b749d835afa7.png)

2021-02-20 00:56 UTC, Olyno commented
Well I would like to tell you it comes from the typing, but after got a look in types, you should not get this error, so... need to have a better look up ahah @EarthAgar

2021-02-20 14:59 UTC, EarthAgar commented
> Well I would like to tell you it comes from the typing, but after got a look in types, you should not get this error, so... need to have a better look up ahah @EarthAgar

I'm somewhat confused on what you're trying to say but also I get that error from a condition in my script that has nothing to do with any mongo documents: `if (level of blast protection of event-slot ? 0) < 5:`

2021-02-20 15:02 UTC, EarthAgar commented
Before using the artifacts that you gave me to test this wasn't an issue but it is now, so I can't really do anything to fix it. Here is a full snippet of my script so that you know I'm not trying to interact with any mongo documents. I will say that the original issue however is fixed and I can add to my list properly.

```
on inventory click:
	if type of player's cursor slot is slime ball:
		if custom model data of player's cursor slot is between 1000 and 1002:
			if "%type of event-item%" contains "helmet" or "chestplate" or "leggings" or "boots":
				cancel event
				if custom model data of player's cursor slot is 1000:
					if (level of blast protection of event-slot ? 0) < 5:
						enchant event-slot with "blast protection %(level of blast protection of event-slot ? 0) + 1%" parsed as enchantment type
						remove 1 of player's cursor slot from player's cursor slot
```

2021-02-20 15:03 UTC, Romitou commented
I can indeed replicate this problem. I will investigate.

2021-02-20 15:07 UTC, EarthAgar commented
> I can indeed replicate this problem. I will investigate.

Thank you <3

2021-02-20 15:15 UTC, Romitou commented
The problem was that part of the syntax had become non-mandatory. I have made it obligatory, and everything should work again now! You can download the fixed version [here](https://github.com/Romitou/MongoSK/suites/2084700883/artifacts/42245455).

2021-02-20 15:37 UTC, EarthAgar commented
> The problem was that part of the syntax had become non-mandatory. I have made it obligatory, and everything should work again now! You can download the fixed version [here](https://github.com/Romitou/MongoSK/suites/2084700883/artifacts/42245455).

Yup that fixed it but it seems to not understand the `first document where` expression anymore.
```
on join:
	set {_doc} to first document where "player" is player's uuid in {players-collection}
```
![image](https://user-images.githubusercontent.com/27425322/108600885-668b9880-734e-11eb-9acb-1616177d2cf2.png)

2021-02-20 15:58 UTC, EarthAgar commented
> > The problem was that part of the syntax had become non-mandatory. I have made it obligatory, and everything should work again now! You can download the fixed version [here](https://github.com/Romitou/MongoSK/suites/2084700883/artifacts/42245455).
> 
> Yup that fixed it but it seems to not understand the `first document where` expression anymore.
> 
> ```
> on join:
> 	set {_doc} to first document where "player" is player's uuid in {players-collection}
> ```
> 
> ![image](https://user-images.githubusercontent.com/27425322/108600885-668b9880-734e-11eb-9acb-1616177d2cf2.png)

I can't seem to `loop all documents` either

2021-02-25 04:10 UTC, EarthAgar commented
Hey tt's been 5 days since the last response, are there any updates?

2021-02-25 08:18 UTC, Romitou commented
Hello, the issue was resolved in the last update 4 days ago. 😄

2021-02-25 21:04 UTC, EarthAgar commented
The initial issue was fixed but some of the syntax isn't working and it prevents me from using some of the syntax. I'm using the latest artifact linked here in this discussion but it seems to be missing some syntax such as `first document`. I already posted images and code of this issue earlier in the discussion.

2021-02-26 23:18 UTC, Romitou commented
I thought version 1.1.3 would have solved your problem. Anyway, I am currently working very hard on version 2.0.0, which should be released in a few days. You will be able to upgrade and enjoy a fully fixed version.

2021-02-27 14:48 UTC, EarthAgar commented
> I thought version 1.1.3 would have solved your problem. Anyway, I am currently working very hard on version 2.0.0, which should be released in a few days. You will be able to upgrade and enjoy a fully fixed version.

That sounds awesome, thank you for the quality plugin and support, I'm happy to wait!