Added a bunch of error messages and made some exceptions return null ...
Romitou/MongoSK pull request #8
Opened 2020-12-21 20:20 UTC by DeltaRays

...  (in the java mongodb driver exceptions are thrown when something is null)

2020-12-21 21:36 UTC, Olyno requested changes
Better with better errors, be carefull to ``return null``, it's a really bad habbit.

2020-12-21 21:36 UTC, Olyno commented on src/main/java/fr/romitou/mongosk/skript/expressions/ExprCollection.java
> +            return null; // A MongoDB collection with that name doesn't exist!
Don't return null when you can
```suggestion
            return new MongoCollection[0]; // A MongoDB collection with that name doesn't exist!
```

2020-12-21 21:36 UTC, Olyno commented on src/main/java/fr/romitou/mongosk/skript/expressions/ExprDatabase.java
> +            return null; // A MongoDB database with that name doesn't exist!
Same here
```suggestion
            return new MongoDatabase[0]; // A MongoDB database with that name doesn't exist!
```

2020-12-21 21:36 UTC, Olyno commented on src/main/java/fr/romitou/mongosk/skript/expressions/ExprValue.java
> +                return null; // That document value doesn't exist;
Same again
```suggestion
                return new Object[0]; // That document value doesn't exist;
```

2020-12-21 21:36 UTC, Olyno commented on src/main/java/fr/romitou/mongosk/skript/expressions/ExprValue.java
> +                return null;
Ah sh*t, here we go again
```suggestion
                return new Object[0];
```

2020-12-22 06:01 UTC, DeltaRays commented
Also thanks Olyno, I always returned null just because mongodb was returning null, too.
When do you think I should use null?

2020-12-22 06:19 UTC, Olyno commented
> When do you think I should use null?

Never, it's a really bad practice which can break a lot of stuff. Skript by default returns everytime ``null``, which is really bad. That's the reason why we changed that for the new parser.
When returning an array, you can simply return a ``new YourObject[0]`` instead of ``null``. When it's not an array but a single object, I would recommand to use ``Optionnals`` of Java 8

2020-12-22 06:21 UTC, DeltaRays commented
Thanks for the info!

2020-12-22 07:46 UTC, Romitou approved these changes

2020-12-22 07:51 UTC, Romitou commented
Many thanks to DeltaRays for the Pull Request and to Olyno for the code reviews! I am merging.

2020-12-22 07:51 UTC, merged